### ISSUE TITLE
Invalid Documentation

### ISSUE THREAD

**Issue by DevThurain** [ibrahimsn98/SmoothBottomBar#115]
how can i setup without option menu 
        binding.navigationBar.setupWithNavController(menu = ????, navcontroller)

**Comment by hrushkoli** [comment]
*Use the following imports*
> import android.view.Menu;
> import android.widget.PopupMenu

# For Java

`private void setupSmoothBottomBar() {`
`        PopupMenu popupMenu = new PopupMenu(this, null);`
`        popupMenu.inflate(R.menu.menu);`
`       Menu menu  = popupMenu.getMenu();`
`      bottomBar.setupWithNavController(menu, navController);`
`    }`
    
 # For Kotlin
 
 `private fun setupSmoothBottomBar() {`
`        var popupMenu : PopupMenu = PopupMenu(this,null)`
`        popupMenu.inflate(R.menu.bottom_nav_menu)`
`        var menu : Menu = popupMenu.menu`
`        bottomBar.setupWithNavController(menu,navController)`
`    }`

**Comment by DevThurain** [comment]
Thanks, I will try to implement it.
