### ISSUE TITLE
How to change background shape?

### ISSUE THREAD

**Issue by abdulazizahwan** [ibrahimsn98/SmoothBottomBar#24]
How to change background shape from drawable resource file,  maybe we want to use custom background that rounded in topLeftCorner and topRightCorner.

**Comment by brookmg** [comment]
Hey @abdulazizahwan, I tried to solve your problem in https://github.com/ibrahimsn98/SmoothBottomBar/pull/27. Check out the latest version and tell us what you think

**Comment by ibrahimsn98** [comment]
You can set border radius to the background now.

**Comment by gargVader** [comment]
@ibrahimsn98 cornerRadius sets radius to not only topRight and topLeft, but all four sides

**Comment by gargVader** [comment]
@brookmg cornerRadius not only changes topRight and topLeft but all four corners which is not intended

**Comment by gargVader** [comment]
@ibrahimsn98 cornerRadius not only changes topRight and topLeft but all four corners which is not intended

**Comment by gargVader** [comment]
As a workaround, I just added a background drawable with the same color and same radius in order to hide the empty white portion at the bottom

**Comment by gargVader** [comment]
![Screenshot_1624467998](https://user-images.githubusercontent.com/52619530/123139137-81445a00-d473-11eb-8076-e464f1ef6b27.png)

**Comment by brookmg** [comment]
This might be a separate issue @gargVader. Can you instead open a new issue and explain the problem there?

**Comment by gargVader** [comment]
Okay. I will do that.

**Comment by gargVader** [comment]
Also is it possible to use SmoothBottomBar with Navigation Components in **java**?

**Comment by gargVader** [comment]
@brookmg

**Comment by brookmg** [comment]
Look at #56 maybe
