### ISSUE TITLE
How to hook up with navController?

### ISSUE THREAD

**Issue by rubek-joshi** [ibrahimsn98/SmoothBottomBar#26]
I am a newbie and am currently working with a single activity and multiple fragments pattern. I want to integrate this smooth bar with the navController.

I tried doing this:
```
bottomBar.onItemSelected = {
            when (it) {
                0 -> navController.navigate(R.id.someFragment)
                1 -> navController.navigate(R.id.someOtherFragment)
                else -> navController.navigate(R.id.someFragment)
            }
        }
```

But this would create a new fragment every time instead of using the existing fragment in the navigation stack. I looked up the documentation and it only teaches how to integrate it with the bottom navigation view they provided.

Is it possible to somehow setup the nav controller? And if not, are there any workarounds?

**Comment by Jeluchu** [comment]
I have exactly the same problem, I'm trying to apply the Navigation Controller to my project and it does not allow me to add it to this type of component

[This is the error it gives me, it tells me that it is not a Bottom Navigation View and I require that](https://drive.google.com/file/d/1GxesxrN7YC0Lr-px94Z7tBWfml9jZgpT/view?usp=sharing)

Thank you very much

Regards!

**Comment by ibrahimsn98** [comment]
Thank you @mayokunthefirst
