### ISSUE TITLE
Dynamically change bottom bar item 

### ISSUE THREAD

**Issue by radheyshyamjat** [ibrahimsn98/SmoothBottomBar#31]
I want to show bottom bar item when user login check type of login user and based on user i want to show 2 tab or 3 tab dynamically change bottom items

**Comment by ibrahimsn98** [comment]
Hi, you can use setActiveItem(pos: Int)

**Comment by radheyshyamjat** [comment]
No no i want to not select dynamically position 
I want to change dashboard items like 
When admin login i want a dashboard item like 1. Dashboard 2. Profile 3. Setting
When client login i want a dashboard item only 2 like 1. Profile 2. Setting not show Dashboard

**Comment by ibrahimsn98** [comment]
Check the release 1.7.5
