### ISSUE TITLE
Not able to implement its dependencies

### ISSUE THREAD

**Issue by shubhamtater** [ibrahimsn98/SmoothBottomBar#34]
I try to add its dependencies in my existing project but its not getting added.

**Comment by dhruvrauthan** [comment]
Have you added these dependencies:
```
    //smoothbottombar
    implementation 'com.github.ibrahimsn98:SmoothBottomBar:1.7.5'

    //navigation components
    implementation "androidx.navigation:navigation-fragment-ktx:2.2.2"
    implementation "androidx.navigation:navigation-ui-ktx:2.2.2"
```

**Comment by brookmg** [comment]
Is adding the jetpack navigation ktx mandatory now?

**Comment by dhruvrauthan** [comment]
Oh, you're right. It's working without the navigation component dependencies as well.

**Comment by brookmg** [comment]
I think the problem is because they didn't add jitpack repository to the repository lookup list.
