### ISSUE TITLE
exposing iconMargin attribute 

### ISSUE THREAD

**Issue by MehdiNosrati** [ibrahimsn98/SmoothBottomBar#35]
Well done, you've done a great work. I was using SmoothBottomBar in my [mTodo](https://github.com/MehdiNosrati/mTodo) and I needed to change the icon margin, but it was not exposed to xml attrs. I had to fork and increase the value inside `Constnats.kt`. It would be nice to have control over it dynamically. I will submit a pull request for that matter. Keep good work up 👌🏻
[PR: #36 ]

**Comment by ibrahimsn98** [comment]
Fixed, thank you :)
