### ISSUE TITLE
Disable text shortening

### ISSUE THREAD

**Issue by titooan** [ibrahimsn98/SmoothBottomBar#37]
Hi, 
Thank you for the great work you've done with this library! 
I use it and it almost fits with the designer's expectations. 

The only problem I'm facing is I need to show the full text without shortening it. 
Is it currently possible? 

If not, I think it could be a nice feature!

**Comment by ibrahimsn98** [comment]
Hi, I think disabling text shortening would create overflow.

**Comment by ibrahimsn98** [comment]
Take a look at #59
