### ISSUE TITLE
I want a java version 

### ISSUE THREAD

**Issue by FlowerFF** [ibrahimsn98/SmoothBottomBar#4]
This library is amazing, I really want to try it, but I won't kotlin.Can you help me?
Thank you.

**Comment by stytooldex** [comment]
setOnItemSelected((Function1<? super Integer, kotlin.Unit>) o -> {

            return null;
        });

**Comment by Uroos** [comment]
Yes I am trying to incorporate this library into my java android project as well but I am stumped. Can't figure out how to setup click listener on it.

**Comment by FlowerFF** [comment]
@Uroos I hope you can succeed.

**Comment by gkhnsgnc** [comment]
See my answer in #9.

**Comment by ibrahimsn98** [comment]
Callbacks has been added for Java. Thank you for support!
