### ISSUE TITLE
1.7.7 not available on jitpack

### ISSUE THREAD

**Issue by FannyDemey** [ibrahimsn98/SmoothBottomBar#69]
Hi ! 
Version released yesterday is not available on jitpack (or elswhere). Any idea why ? 
Thanks to your help :) 
👋

**Comment by ibrahimsn98** [comment]
Hey,
https://jitpack.io/#ibrahimsn98/SmoothBottomBar/1.7.7 It looks available

**Comment by FannyDemey** [comment]
Oh yes sounds better than when I tried. Sorry for the inconvenience.

Le mer. 17 mars 2021 à 16:24, İbrahim Süren ***@***.***> a
écrit :

**Comment by ibrahimsn98** [comment]
No problem :)
