### ISSUE TITLE
setSelectedItem?

### ISSUE THREAD

**Issue by afsc19** [ibrahimsn98/SmoothBottomBar#71]
Hello, I'm developing an app which contains Smooth Bottom Bar.
I'd like to keep the selected item when the app re-opens. For that I save the selected item in shared preferences and re-use it on re-open. I replace the fragment I want, but the bottom bar doesn't have any function to select the item or to 'fakeclick' programmatically.
Thanks in advance, -afsc.

**Comment by brookmg** [comment]
Have you tried `setActiveIndex`?

**Comment by paktech1** [comment]
bottomBar.itemActiveIndex = position worked for me, thanks.

**Comment by milon27** [comment]
bottomBar.itemActiveIndex = position **doesn't change the fragment** .

**Comment by milon27** [comment]
this will work.
```
binding.bottomNavId.itemActiveIndex=1
navCon.navigate(R.id.twoFragment)
```

**Comment by milon27** [comment]
Implement that features on this pull : [pull request added select iem](https://github.com/ibrahimsn98/SmoothBottomBar/pull/83)

@afsc19 
@paktech1 
@brookmg

**Comment by m1faridi** [comment]
Menu menuBottom ;


bottomNavigationView.setItemActiveIndex(3);
NavigationUI.onNavDestinationSelected(menuBottom.getItem(3), navController);    


private void setupSmoothBottomBar() {
        PopupMenu popupMenu = new PopupMenu(this, null);
        popupMenu.inflate(R.menu.menu_bottom);
        menuBottom = popupMenu.getMenu();
        bottomNavigationView.setupWithNavController(menuBottom, navController);
    }
