### ISSUE TITLE
Nav Menu Visibility Respect to Login

### ISSUE THREAD

**Issue by amiyo-biswas-mongia** [ibrahimsn98/SmoothBottomBar#74]
I've 3 fragments. Where `FragmentC` known as  **Login Fragment**.

` FragmentA - FragmentB - FragmentC`

If **`FragmentC`** successfully logged in then it redirect to **`FragmentProfile`**.

`findNavController().navigate(R.id.fragment_profile)`

If user back to on this time then it redirect to `FragmentA`. 

`findNavController().navigateUp()`

Now my question is, In that case Bottom Fragment will be

 ` FragmentA - FragmentB - FragmentProfile`

Above scenario is not occur.  How can I replace `FragmentC` to `FragmentProfile`.

**Comment by amiyo-biswas-mongia** [comment]
Is there any `updateBottomNavigationMenu()` present ?

**Comment by kumarasamy92** [comment]
How do you fix this issue?
