### ISSUE TITLE
Hiding back button toolbar

### ISSUE THREAD

**Issue by 1902shubh** [ibrahimsn98/SmoothBottomBar#76]
How to hide back button tool bar

**Comment by 1902shubh** [comment]
I got my answer

   `NavigationUI.setupActionBarWithNavController(this,navController);`
we can do this by not writing this line

**Comment by thomassamoul** [comment]
can you explain please how u do that

**Comment by 1902shubh** [comment]
Uncomment that line that i mention above or share your code i will check
and tell you
