### ISSUE TITLE
Reference bottom bar menu item ID for ShowcaseView target

### ISSUE THREAD

**Issue by Glutius** [ibrahimsn98/SmoothBottomBar#87]
I've spend the whole day trying and searching on how to get the bar's view and reference one of the tabs, just so I can use it as a target in [MaterialShowcaseView](https://github.com/deano2390/MaterialShowcaseView), to use in a user tutorial.
![image](https://user-images.githubusercontent.com/12672076/123713928-1ed9c800-d87e-11eb-8f49-b2a72a0880ed.png)
I wont add code, as I have it set up the same with the [(Use SmoothBottomBar with Navigation Components.)](https://github.com/ibrahimsn98/SmoothBottomBar#use-smoothbottombar-with-navigation-components), but in java.
![image](https://user-images.githubusercontent.com/12672076/123714482-10d87700-d87f-11eb-91d4-0832b0d6647c.png)

I love this bar, and the MaterialShowcaseView as it can help guide the first time user, but been stuck on this for a while now. Any help is appreciated

**Comment by Glutius** [comment]
No longer need this. Closing.

**Comment by henrichg** [comment]
Please I need this. How to get item view? Thank you

**Comment by brookmg** [comment]
Hey @Glutius, Can you show how you solved this issue? If you did that is.

**Comment by Glutius** [comment]
I didn't find a way to do that exactly, but instead of showing the user the bar, I made a full user intro in the beginning that explains everything in the first screen, then after the last tip, changes to the second tab/screen and continues the tips/tutorial and so on for each screen.
imo, this is better if you wanna explain some stuff in order, rather than the tips opening in which order the user presses the tabs.

**Comment by henrichg** [comment]
Hm, not good. Currently I have commented tap target for SmothBottomBar items. Maybe it s not problem for users. :-)
But thank you for help.
