### ISSUE TITLE
I want onItemSelected function for Java

### ISSUE THREAD

**Issue by akku20080** [ibrahimsn98/SmoothBottomBar#9]
Hello i tried this library for my project, but I am unable to use onItemSelected function. Instead i get setOnItemSelected function but couldn't understand it as to how to use it. Please help.  How do i switch fragment when bottombar item changes, in Java. Please help.

**Comment by stytooldex** [comment]
setOnItemSelected((Function1<? super Integer, kotlin.Unit>) o -> {

            return null;
        });

**Comment by xDragonZ** [comment]
Drop in replacement for `com.google.android.material.tabs.TabLayout` too or able to use with `androidx.viewpager.widget.ViewPager`

**Comment by gkhnsgnc** [comment]
After you configure your project to use Kotlin (see `Tools > Kotlin > Configure Kotlin in Project`), create a Function1 instance in your Activity:

```
Function1 onItemSelected = new Function1() {
	@Override
	public Object invoke(Object o) {
		int position = (int) o;

		// use position as you want.

		return position;
	}
};
```

And set it as listener:

`bottomBar.setOnItemSelected(onItemSelected);`

**Comment by ibrahimsn98** [comment]
Callbacks has been added for Java. Thank you for support!
