### ISSUE TITLE
wrong dependency in new Build.gradle

### ISSUE THREAD

**Issue by Vishal-beep136** [ibrahimsn98/SmoothBottomBar#90]
How to implement in the new version of Build.Gradle

**Comment by AleP04** [comment]
I successfully implemented the SmootBottomBar by modifying the settings.gradle file.
As the creator suggest you should add `maven { url 'https://jitpack.io' }` in both buildscript and allprojects, but when I tried to add it in allproject the Gradle Build Tool showed me an error. So I found that you have to:

1) Add implementation in build.gradle (Module)
2) Add maven { url 'https://jitpack.io' } in repositories of both buildscript and allproject (if the last one isn't present write it yourself)
**3) Change che settings.gradle file, in particular:
    1) Commenting the repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS) like this
     //repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    2) Changing repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS) to 
        repositoriesMode.set(RepositoriesMode.PREFER_PROJECT

4)Resynch Gradle**


I hope this was helpful.
_I made it work with "org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.21"_

**AlePSDev**

**Comment by ArleyPereira** [comment]
I did as specified above and gave an error

```
Could not find org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.21.
Required by:
    project :app
Search in build.gradle files
```

**Comment by mofaizanfdns** [comment]
> I did as specified above and gave an error
> 
> ```
> Could not find org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.21.
> Required by:
>     project :app
> Search in build.gradle files
> ```

I Got same issue

**Comment by mofaizanfdns** [comment]
> I did as specified above and gave an error
> 
> ```
> Could not find org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.21.
> Required by:
>     project :app
> Search in build.gradle files
> ```

I Got same issue and resolved it by adding this line in build.gradle ( Module ) in 
> buildscript {
>       ......
>   dependencies {
>        .......
>      classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.32"
>    }
> }

**Comment by tandacedric** [comment]
My root build.gradle
![image](https://user-images.githubusercontent.com/13773515/133906245-e1473702-32b3-434b-8228-da550e61998f.png)
My settings.gradle

![image](https://user-images.githubusercontent.com/13773515/133906255-5e4828f5-df6f-4f9f-b91f-eca3ebcb47b8.png)

**Comment by Deepak-Yadav-01** [comment]
@tandacedric this works for me also. Thank you
